<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	
	<ImplicitUsings>enable</ImplicitUsings>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>

	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	<ApplicationIcon>kon'.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="resources\About.html" />
    <None Remove="resources\Grammar.html" />
    <None Remove="resources\Help.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Markdig" Version="1.0.0" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="kon'.ico" />
		<Content Include="parser.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>false</ExcludeFromSingleFile>
			<AssetType>native</AssetType>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="resources\About.html" />
	  <EmbeddedResource Include="resources\Grammar.html" />
	  <EmbeddedResource Include="resources\Classification.html" />
	  <EmbeddedResource Include="resources\Help.html" />
	  <EmbeddedResource Include="resources\References.html" />
	  <EmbeddedResource Include="resources\Method.html" />
	  <EmbeddedResource Include="resources\Tests.html" />
	  <EmbeddedResource Include="resources\Task.html" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ParserANTLR\ParserANTLR.csproj" />
	</ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="parser.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>